### ISSUE TITLE
No symbol occurrence for string literal arguments to `import` statements

### ISSUE THREAD

**Issue by coury-clark** [sourcegraph/scip-typescript#174] opened 2022-10-05 17:59 UTC
Sometimes components might be referenced indirectly through a string, as an example [CodeMirrorMonacoFacade](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/search-ui/src/input/LazyMonacoQueryInput.tsx?L21)

Currently there is no hover or ability to go to definition / references, but this is available in IDEs (see below)

![CleanShot 2022-10-05 at 08 24 16](https://user-images.githubusercontent.com/5090588/194129327-56bf23fe-43b3-4d5d-87ba-f3c2111ee7ed.gif)

**Comment by olafurpg** [comment] 2022-10-05 18:03
Thank you for reporting! I'm able to reproduce. 

I'm a but curious how IntelliJ handles `CodeMirrorMonacoFacade` because the argument has type string and `lazyComponent` is a custom function, it's not a builtin like `import`. The TypeScript language server doesn't support goto definition for `CodeMirrorMonacoFacade` either. 

I'm not sure we 
```ts
import('./CodeMirrorQueryInput'), 'CodeMirrorMonacoFacade')
```

However, we should definitly support goto definition for `import('LITERAL')` statments!

**Comment by felixfbecker** [comment] 2022-10-05 22:57
I'd say this is more our fault in writing this custom helper this way, I think VS Code, which uses the official tsserver, doesn't support this either. It may be very rare the way it's written.

Note how the `lazyLoadComponent()` function also doesn't receive the string for the module path – `import()` is called by the caller, because that is needed for better code intelligence/type safety. The same should really be done here with the component too.

The better pattern would be:
```ts
lazyLoadComponent(import('xyz').then(m => m.MyComp))
// or
lazyLoadComponent(import('xyz').then(({ MyComp }) => MyComp))
``` 

That way you could jump to `MyComp` properly.

**Comment by olafurpg** [comment] 2022-10-18 11:28
Closing this with #184, which adds support to navigate to string literals of `import` statements. @coury-clark the [CodeMirrorMonacoFacade](https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/search-ui/src/input/LazyMonacoQueryInput.tsx?L21) example still does not work and it's unlikely to ever work with scip-typescript, but we could try to implement this with search-based intel (which I'm guessing is similar what WebStorm is doing here).

Update to https://github.com/sourcegraph/scip-typescript/releases/tag/v0.3.0 to try it out! I'm guessing our CI automatically picks up the new version

**Closed as completed by olafurpg** 2022-10-18 11:28 UTC
Labels: team/language-tools
